import { Inter } from "next/font/google";
import "./globals.css";
import { cookies } from "next/headers";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const theme = cookies().get("theme");
  console.log({ theme });
  return (
    <html lang="en" className={theme?.value}>
      <body
        className={`bg-white
        text-black
        dark:bg-black
        dark:text-white
        transition
        duration-700"`}
      >
        {children}
      </body>
    </html>
  );
}
